version: 2

jobs:
  build:
    working_dictionary: ~/Network_API/API_1
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python --version
  test:
    working_dictionary: ~/Network_API/API_1
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python client_test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build