version: 2

jobs:
  build:
    working_dictionary: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python --version
  test:
    working_dictionary: ~
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run: python -m unittest test.unit.HTTP_test
      - run: python -m unittest test.unit.TCP_test
      - run: python -m unittest test.unit.UDP_test
      - run: python -m unittest test.unit.IPGenerator_test
      - run: python -m unittest test.unit.xmlrpc_test
      - run: python -m unittest test.unit.ssl_test
      - run: python -m unittest test.integrate.service_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build